### ISSUE TITLE
We reuse a `KeyboardRow` in the loop for the food

### ISSUE THREAD

**Issue by appsandappsandapps** [nmnm220/WhoFeedTheCatBotTest#1]
We [reuse](https://github.com/nmnm220/WhoFeedTheCatBotTest/blob/master/src/main/java/io/proj3ct/WhoFeedTheCatBot/service/TelegramBot.java#L70) a `KeyboardRow` when we add to the list of keyboard rows. This is the cause of the strange issue in the lesson today.

Please make a new branch and then commit that branch. In the console, it should give you a URL in which to create a new "Pull request". Assign me to a reviewer of the pull request.

Thanks!

**Comment by nmnm220** [comment]
Added a new branch with fix
