### ISSUE TITLE
It's possible multiple if statements could be run in updateMessage()

### ISSUE THREAD

**Issue by appsandappsandapps** [nmnm220/WhoFeedTheCatBotTest#2]
Look at https://github.com/nmnm220/WhoFeedTheCatBotTest/blob/069c49d7ba3adebde92081d3043d6d4169b445c7/src/main/java/io/proj3ct/WhoFeedTheCatBot/service/TelegramBot.java#L54

Altough it doesn't happen now, in future multiple if statements could be run, that is, multiple command could be run, something we almost certainly don't want.

How can you change it to ensure only one brance is run?

**Comment by nmnm220** [comment]
Created pull request  #4.
